#!/usr/bin/env bash
# setup-env.sh — Auto-detect JAVA_HOME and GHIDRA_INSTALL_DIR, write .env
# Usage: ./setup-env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "🔍 Detecting development environment..."

# --- Detect JAVA_HOME (need JDK 21) ---
detect_java() {
  # 1. Already set and valid?
  if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/javac" ]; then
    echo "$JAVA_HOME"
    return
  fi

  # 2. macOS java_home utility
  if command -v /usr/libexec/java_home &>/dev/null; then
    local jh
    jh=$(/usr/libexec/java_home -v 21 2>/dev/null || true)
    if [ -n "$jh" ] && [ -x "$jh/bin/javac" ]; then
      echo "$jh"
      return
    fi
  fi

  # 3. Homebrew OpenJDK 21
  local brew_jdk
  for brew_jdk in /opt/homebrew/Cellar/openjdk@21/*/libexec/openjdk.jdk/Contents/Home \
                   /usr/local/Cellar/openjdk@21/*/libexec/openjdk.jdk/Contents/Home; do
    if [ -x "$brew_jdk/bin/javac" ] 2>/dev/null; then
      echo "$brew_jdk"
      return
    fi
  done

  # 4. sdkman
  local sdk_jdk
  for sdk_jdk in "$HOME"/.sdkman/candidates/java/21.*; do
    if [ -x "$sdk_jdk/bin/javac" ] 2>/dev/null; then
      echo "$sdk_jdk"
      return
    fi
  done

  return 1
}

# --- Detect GHIDRA_INSTALL_DIR ---
detect_ghidra() {
  # 1. Already set and valid?
  if [ -n "${GHIDRA_INSTALL_DIR:-}" ] && [ -f "$GHIDRA_INSTALL_DIR/ghidraRun" ]; then
    echo "$GHIDRA_INSTALL_DIR"
    return
  fi

  # 2. Homebrew
  local brew_ghidra
  for brew_ghidra in /opt/homebrew/Cellar/ghidra/*/libexec \
                     /usr/local/Cellar/ghidra/*/libexec; do
    if [ -f "$brew_ghidra/ghidraRun" ] 2>/dev/null; then
      echo "$brew_ghidra"
      return
    fi
  done

  # 3. Follow ghidraRun on PATH
  if command -v ghidraRun &>/dev/null; then
    local resolved
    resolved="$(readlink -f "$(command -v ghidraRun)" 2>/dev/null || true)"
    if [ -n "$resolved" ]; then
      echo "$(dirname "$resolved")"
      return
    fi
  fi

  # 4. Common install locations
  local loc
  for loc in /opt/ghidra /opt/ghidra/*/  \
             "$HOME/ghidra" "$HOME/ghidra/"*/ \
             /Applications/ghidra/*/; do
    if [ -f "$loc/ghidraRun" ] 2>/dev/null; then
      echo "$loc"
      return
    fi
  done

  return 1
}

# --- Run detection ---
FOUND_JAVA=""
FOUND_GHIDRA=""
ERRORS=0

if FOUND_JAVA=$(detect_java); then
  echo "  ✅ JAVA_HOME=$FOUND_JAVA"
else
  echo "  ❌ Could not find JDK 21. Install with: brew install openjdk@21"
  ERRORS=1
fi

if FOUND_GHIDRA=$(detect_ghidra); then
  echo "  ✅ GHIDRA_INSTALL_DIR=$FOUND_GHIDRA"
else
  echo "  ❌ Could not find Ghidra. Install with: brew install ghidra"
  ERRORS=1
fi

if [ "$ERRORS" -ne 0 ]; then
  echo ""
  echo "Fix the issues above, then re-run this script."
  exit 1
fi

# --- Write .env ---
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-env.sh — edit freely
JAVA_HOME=$FOUND_JAVA
GHIDRA_INSTALL_DIR=$FOUND_GHIDRA
EOF

echo ""
echo "✅ Wrote $ENV_FILE"
echo "   Run ./dev-install.sh to build and launch."
